### ISSUE TITLE
Migrate imports to collections.abc

### ISSUE THREAD

**Issue by dhimmel** [xlcnd/isbnlib#61]
Got the following warning on [our CI build](https://travis-ci.com/manubot/manubot/jobs/247602793#L770):

```
  /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/isbnlib/_imcache.py:4: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import MutableMapping
```

The issue is the following line:

https://github.com/xlcnd/isbnlib/blob/c9a4bbf88e8002e44a6efaf983f3d8e8797a0a59/isbnlib/_imcache.py#L4

Haven't checked whether any other imports in the package need to be moved to `collections.abc`, but with Python 3.8 just released, these imports will start failing.

**Comment by xlcnd** [comment]
Thanks! Already fixed in 'dev' branch.

**Comment by dhimmel** [comment]
Still getting warnings when installing the [latest version](https://pypi.org/project/isbnlib/3.9.9/) from PyPI. Do you plan to release a version soon that doesn't result in warnings?

**Comment by xlcnd** [comment]
As I said in the comment above, this is issue is already fixed in the 'dev' branch. In a few days I will make and release a new version from it.
